"""removed UK from upload image

Revision ID: 035a43aecf9a
Revises: f563e4aa22b7
Create Date: 2022-01-05 18:51:23.538360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035a43aecf9a'
down_revision = 'f563e4aa22b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('upload_image_user_id_key', 'upload_image', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('upload_image_user_id_key', 'upload_image', ['user_id'])
    # ### end Alembic commands ###
