"""otp bug solved

Revision ID: 9d8bf62d8635
Revises: e9614fd18da1
Create Date: 2022-01-03 23:00:55.037250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d8bf62d8635'
down_revision = 'e9614fd18da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp', sa.Column('otp', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp', 'otp')
    # ### end Alembic commands ###
