"""convert int to str in user and otp table

Revision ID: a44f226a2764
Revises: f6d0c2c43160
Create Date: 2022-01-05 08:13:19.729840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a44f226a2764'
down_revision = 'f6d0c2c43160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
