"""convert int to str

Revision ID: f563e4aa22b7
Revises: fd3c991ac305
Create Date: 2022-01-05 08:18:48.593266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f563e4aa22b7'
down_revision = 'fd3c991ac305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users ALTER COLUMN number TYPE VARCHAR(10)")
    op.execute("ALTER TABLE otp ALTER COLUMN otp TYPE VARCHAR(6)")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
