"""convert int to str

Revision ID: fd3c991ac305
Revises: a44f226a2764
Create Date: 2022-01-05 08:16:51.633221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd3c991ac305'
down_revision = 'a44f226a2764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
